spring:
  config: 
    activate:
      on-profile: qa

server: 
  servlet: 
    context-path: /eureka-server
    
eureka:
  environment: QA
  instance: 
    hostname: v4.auradocs.com
  client:
    serviceUrl: 
      defaultZone: https://${eureka.instance.hostname}/${server.servlet.context-path}/eureka
  