server:
  port: 8761
  
spring:
  profiles:
    active: dev
  banner: 
    location: classpath:banner.txt
    
eureka:
  # client:
    # register-with-eureka: false
    # fetch-registry: false
  datacenter: Colombo-SriLanka
  renewalPercentThreshold: 0.85