server:
  port: 9191
  servlet:
    context-path: /api

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/auradocs_auradot?createDatabaseIfNotExist=true&allowPublicKeyRetrieval=true&useSSL=false
    username: root
    password: Admin@123
  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      ddl-auto: update

eureka:
  instance:
    hostname: auradocsv4.southindia.cloudapp.azure.com

member:
  rent:
    min: 10
    max: 33
  price:
    discount: 3
vehicle:
  default:
    model: cross over
duration: all
