server:
  port: 9191
  servlet:
    context-path: /api
  ribbon:
    eureka: 
      enabled: true

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/auradocs_auradot?createDatabaseIfNotExist=true&allowPublicKeyRetrieval=true&useSSL=false
    username: root
    password: Admin@123
  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      ddl-auto: update

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761//eureka-server/eureka # ${EUREKA_URI:https://v4.auradocs.com/eureka-server/eureka}
  instance:
    preferIpAddress: true
    instance-id: ${spring.application.name}-${random.int}
    # hostname: localhost

member:
  rent:
    min: 10
    max: 33
  price:
    discount: 3
vehicle:
  default:
    model: cross over
duration: all
