spring:
  elasticsearch:
    uris: http://localhost:9200
    # username: elastic
    # password: ${ELASTIC_SEARCH_PW}

member:
  rent:
    min: 8
    max: 31
  price:
    discount: 3
vehicle:
  default:
    model: cross over
duration: all
