spring:
  data:
    elasticsearch:
      cluster-name: elasticsearch
      cluster-nodes: localhost:9200
      repositories:
        enabled: true

eureka:
  instance:
    hostname: auradocsv4.southindia.cloudapp.azure.com

member:
  rent:
    min: 10
    max: 33
  price:
    discount: 3
vehicle:
  default:
    model: cross over
duration: all
