spring:
  data:
    elasticsearch:
      cluster-name: elasticsearch
      cluster-nodes: localhost:9200
      repositories:
        enabled: true
  mail:
    host: 74.55.132.178
    # port: 587 / 465
    username: auradocs@auradot.com
    password: auradot@123
    properties:
      mail: 
        smtp: 
          auth: true
          starttls:
            enable: true

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka-server/eureka # ${EUREKA_URI:https://v4.auradocs.com/eureka-server/eureka}
    healthcheck:
      enabled: true
  instance:
    preferIpAddress: true
    instance-id: ${spring.application.name}-${random.int}
    # hostname: localhost

member:
  rent:
    min: 10
    max: 33
  price:
    discount: 3
vehicle:
  default:
    model: cross over
duration: all
