spring:
  # elasticsearch:
  #   uris: http://localhost:9200
  #   username: elastic
  #   password: ${ELASTIC_SEARCH_PW}

  data:
    elasticsearch:
      cluster-name: elasticsearch
      cluster-nodes: localhost:9200
      repositories:
        enabled: true

eureka:
  instance:
    hostname: localhost

member:
  rent:
    min: 8
    max: 31
  price:
    discount: 3
vehicle:
  default:
    model: cross over
duration: all
