spring:
  data:
    elasticsearch:
      cluster-name: elasticsearch
      cluster-nodes: localhost:9200
      repositories:
        enabled: true

# eureka:
#   instance:
#     hostname: v4.auradocs.com/discovery/

member:
  rent:
    min: 10
    max: 33
  price:
    discount: 3
vehicle:
  default:
    model: cross over
duration: all
